export enum StorageKeys {
    AuthToken = 'AuthToken',
    UniqueUserId = 'UniqueUserId',
    UserId = 'UserId',
    UserEmail = 'UserEmail',
    OnBoardingIsDone = 'OnBoardingIsDone',
    FbSignInRulesAccepted = 'FbSignInRulesAccepted',
    GoogleSignInRulesAccepted = 'GoogleSignInRulesAccepted',
    PostDrafts = 'PostDrafts',
    QueuedPosts = 'QueuedPosts',
    PushMessages = 'PushMessages',
    applicationHasRated = 'hasRated',
    themeVersion = 'theme',
    autoTheme = 'autoTheme',
    NotificationPermissionHasAsked = 'notificationPermissionHasAsked',
    SocialMediaHasAsked = 'socialMediaHasAsked',
    AvatarHasAsked = 'avatarHasAsked',
    LocationPermissionHasAsked = 'locationPermissionHasAsked',
    TrackingStatus = 'trackingStatus',
    CustomPushMsgId = 'customPushMsgId',
    SocietyApi = 'SocietyApi',
    SocietyId = 'SocietyId',
    UserIdWithSociety = 'UserIdWithSociety',
}
